### ISSUE TITLE
Miscellaneous text block showing up in admin

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#84] opened 2019-10-25 13:50 UTC
See screenshot. Baffling.

<img width="949" alt="Screen Shot 2019-10-15 at 3 38 52 PM" src="https://user-images.githubusercontent.com/10144772/67576620-e549d480-f70c-11e9-9110-c519ad1d3864.png">

**Comment by iambateman** [comment] 2019-10-25 17:29
did that happen for you?

**Comment by iambateman** [comment] 2019-11-16 16:19
I have no idea how to debug this, since I can't reproduce on my machine. For now I'm requesting that we close this, or try to get more info on what happened..

**Comment by ggordn3r** [comment] 2019-11-18 20:37
I'm reassigning this back to FairVote. Let's check together with Emily on our next call to make sure this has been resolved.

**Closed** 2019-11-26 20:34 UTC
Labels: bug
