### ISSUE TITLE
As a poll creator, I can export results to RCVIS via API

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#116] opened 2020-04-30 15:34 UTC
#99 enabled this via CSV download/upload. Now we're looking to take out a step.

Armin, the developer on RCVIS, is willing to integrate directly if we can pipe out the JSON created by the tabulation. It looks something like this:
https://github.com/artoonie/rcvis/blob/master/testData/medium-rcvis.json

- Under the "Download results (CSV)" button, add "Export results to RCVIS"
- This button should be disabled when polls are open and enabled when polls are closed.

To coordinate with Armin, email armin.samii@gmail.com

**Comment by proggeramlug** [comment] 2020-07-08 17:54
Okay, this is now on rankit.skelpo.com ! 

It (for now) only outputs the JSON. Waiting for Armin to provide me with an endpoint.

**Comment by ggordn3r** [comment] 2020-07-10 19:53
I tried downloading the JSON results from a poll and uploading them to https://www.rcvis.com/upload.html but received the error below:

```
Cannot parse that JSON file!

Did it come from opavote or the RCVRC universal tabulator? If so, please contact us with the JSON and how you obtained it, and we will try to figure this out together:

Preferred method: Make an issue on Github Issues

Email: team@rcvis.com
```

Here is the JSON that was generated:

`{"config":{"contest":"Which is the better hardware store","date":"52313-12-27","jurisdiction":"","office":"","threshold":2},"results":[{"round":1,"tally":{"Lowes":1,"Home Depot":1},"tallyResults":[{"elected":"Home Depot"}]}]}`

Can you confirm the format is correct while we wait for the endpoint?

**Comment by proggeramlug** [comment] 2020-08-05 16:01
This is now implemented to the point that we are successfully uploading to RCVIS - however, I do not know yet how we get the link to show the visualization. Or can you specify what we want to do with this once uploaded?

**Comment by ggordn3r** [comment] 2020-08-06 17:47
Armin's URL provides the expected behavior. I should immediately see my poll results in his visualizations:
https://rcvis.com/visualize=results18json-1

Sounds like you're waiting on him to add that to the API.

In the meantime, two errors to be fixed:

1) The button should say "Export Results to RCVIS" and use the icon `fa fa-share-alt`

2) I'm unable to test the current behavior because I'm getting authorization issues in the Console:
![image](https://user-images.githubusercontent.com/10144772/89564203-a93eb680-d7ea-11ea-8ac4-347fa6db2abc.png)

**Comment by proggeramlug** [comment] 2020-08-10 16:14
Okay, Armin delivered what we need and now it should work as expected. :)

**Comment by ggordn3r** [comment] 2020-08-12 14:21
Still getting an error in console on some tested polls.

I got this while logged in as an admin, both on a poll I created and one built by another user:

![Screenshot (27)](https://user-images.githubusercontent.com/10144772/90026592-82b6ca80-dc85-11ea-87e7-c526c87b8a1f.png)

When I logged in as a non-admin user, it failed the first time I clicked, but when I clicked again it opened the visualization in a new tab as expected. Here's the console from that session. 

![Screenshot (28)](https://user-images.githubusercontent.com/10144772/90026910-f22cba00-dc85-11ea-96a1-cc5cec04091d.png)

**Comment by proggeramlug** [comment] 2020-08-12 20:59
Found one bug and fixed it - I think that might be the one responsible for your problems - try again please.

**Comment by ggordn3r** [comment] 2020-08-13 13:57
The polls are now going through, which is great. However, there seem to be some discrepancies between our tabulation and their visualization. See, for example:

4 Rounds on RankIt: https://rankit.skelpo.com/results/OpdLCmLbgPv60lRs9ngq/summary
1 Round on RCVIS: https://www.rcvis.com/v/data-10

5 Rounds on Rankit: https://rankit.skelpo.com/results/rDZnWYOUBh5BbaSUvF1b/summary
2 Rounds on RCVIS: https://www.rcvis.com/v/data-11

Are we passing over round-by-round data? If so, how is this possible? Expected behavior is that the number of rounds (and votes for each candidate in each round) are the same in both places.

**Comment by proggeramlug** [comment] 2020-08-13 18:10
there was one bug not showing all rounds, however, there is another problem: What we are doing doesn't seem to fit the visualizer. For example here: https://rankit.skelpo.com/results/OpdLCmLbgPv60lRs9ngq/summary

We have 4 rounds but only one winner (in the first round). So the other rounds are (at least in the database) somewhat empty, no one is eliminated nor is anyone winning. The elimination part we can probably figure out because correct me if I am wrong but someone is always eliminated?

But that's the problem now, can you check what to do best?

**Comment by ggordn3r** [comment] 2020-08-13 20:33
Hey Ralph--that's incorrect. You linked to the Final Results (/summary) but we should be piping over all rounds.

If you click "See Results by Round" you'll see that there is no winner in the first round:
https://rankit.skelpo.com/results/OpdLCmLbgPv60lRs9ngq/1

Rather, it takes 4 rounds to get to a winner:
https://rankit.skelpo.com/results/OpdLCmLbgPv60lRs9ngq/4

Maybe you're looking at the wrong object?

**Comment by proggeramlug** [comment] 2020-08-14 17:34
Okay, I think I finally figured this out. The problem here had to do with how we capture results. The PR I just merged today is taking care of this though, so going forward this is fixed. 

2 important notes here:
1. Only polls where a *new* vote has been submitted (so the results have been recalculated) are going to show effect here.
2. I tried to keep old polls working but we need _TESTING_ here.

**Comment by ggordn3r** [comment] 2020-08-14 22:25
Getting closer. I interpreted your comment as you wanted me to test old polls first, so here's what I found:

When I tested this poll again, I got about:blank in a new tab. Tried twice.
https://rankit.skelpo.com/polls/rDZnWYOUBh5BbaSUvF1b

When I tested this poll again, the rounds came through! However, it looks like the vote counts didn't:
https://rankit.skelpo.com/polls/OpdLCmLbgPv60lRs9ngq
The vote totals for each round in our results are changing with the percentages:
https://rankit.skelpo.com/results/OpdLCmLbgPv60lRs9ngq/1
But the vote totals in the RCVIS visualizations stay static every round:
https://www.rcvis.com/v/data-17#tabular-candidate-by-round

**Comment by proggeramlug** [comment] 2020-08-14 22:33
Hmm, probably an error in the import. We are delivering this here:
```json
{
  "config": {
    "contest": "What movie should we watch on Friday night?",
    "date": "2020-07-29",
    "jurisdiction": "RankIt Export",
    "office": "None given",
    "threshold": "9"
  },
  "results": [
    {
      "round": 1,
      "tally": {
        "Monty Python and the Holy Grail": "1",
        "Wayne's World": "4",
        "Naked Gun": "6",
        "Bill and Ted Excellent Adventure": "2",
        "Spaceballs": "4"
      },
      "tallyResults": [
        {
          "eliminated": "Monty Python and the Holy Grail"
        }
      ]
    },
    {
      "round": 2,
      "tally": {
        "Wayne's World": "4",
        "Naked Gun": "6",
        "Spaceballs": "4",
        "Bill and Ted Excellent Adventure": "3"
      },
      "tallyResults": [
        {
          "eliminated": "Bill and Ted Excellent Adventure"
        }
      ]
    },
    {
      "round": 3,
      "tally": {
        "Wayne's World": "5",
        "Spaceballs": "5",
        "Naked Gun": "7"
      },
      "tallyResults": [
        {
          "eliminated": "Wayne's World"
        }
      ]
    },
    {
      "round": 4,
      "tally": {
        "Spaceballs": "7",
        "Naked Gun": "8"
      },
      "tallyResults": [
        {
          "elected": "Naked Gun",
          "eliminated": "Spaceballs"
        }
      ]
    }
  ]
}
```

Notice how in round 3 we are defining "7" votes but the chart only shows 6?

**Comment by ggordn3r** [comment] 2020-08-14 22:50
Ok, I'll email Armin about it.

**Comment by ggordn3r** [comment] 2020-08-17 15:05
Armin got back to us--sounds like his algorithm expects an explicit "transfer" variable. Refer back to his email, I'll let you take it from here.

**Comment by proggeramlug** [comment] 2020-08-18 07:51
I think the transfer object works for us - check it out!
https://www.rcvis.com/v/data-21

(It's already ready to test)

**Comment by ggordn3r** [comment] 2020-08-25 16:32
Both users testing this report that when they click "Export Results to RCVIS, it opens a new tab but goes to about:blank instead of the expected URL on RCVIS:

![2020-08-25](https://user-images.githubusercontent.com/10144772/91201862-fa95e380-e6ce-11ea-95fc-ee25a89caef8.png)

**Comment by proggeramlug** [comment] 2020-08-27 00:36
That's the dcase if there is a problem - can we get the poll IDs to reproduce?

**Comment by ggordn3r** [comment] 2020-08-27 02:58
Here are the two polls reported:
https://rankit.skelpo.com/polls/eaub53HYQM70lX5J8az7
https://rankit.skelpo.com/polls/wTmvs5mhEozssqqk3Unh

**Comment by proggeramlug** [comment] 2020-08-27 03:39
I've adjusted it so that instead of an empty window there will be a download. This download we can debug then. In these cases I have no idea what the problem is, I'll ask Armin.

**Comment by proggeramlug** [comment] 2020-08-27 15:35
Okay, found the problem for those too and fixed it!

**Comment by ggordn3r** [comment] 2020-09-01 00:08
Tester reported the following. Looks like something may be wrong with the transfer object during surplus transfers and/or the export currently isn't able to define multiple winners in 1 round.

> I retested the export feature using this poll: https://rankit.skelpo.com/results/wTmvs5mhEozssqqk3Unh/summary
> Here is the URL for the exported data: https://www.rcvis.com/v/data-30
> 
> The issues I have experienced with it so far are:
> 
> · None of the display options in RCVIS recognize that ‘The Wasted Vote’ is a winner, even though it had the most first-choice votes and passed the victory threshold for a 3 winner poll (screenshot 3). In contrast, Rankit does recognize it as a winner
> 
> · It isn’t clear what RCVIS is doing in the second round, since the display looks exactly the same as round 1 (screenshots 1 and 2). In round two on rankit.skelpo.vote, it was doing a  surplus reallocation. Maybe RCVIS has a hard time visualizing the surplus reallocation step.

**Comment by proggeramlug** [comment] 2020-09-01 08:40
Found the problem and fixed it!

**Comment by proggeramlug** [comment] 2020-09-01 08:40
Need to reexport of course

**Comment by ggordn3r** [comment] 2020-09-04 14:57
Ok, something odd happened. He gave me this link to retest:
https://www.rcvis.com/v/data-39#barchart-interactive

But it's a totally different poll than the one at the same URL in his screenshot below:
![Round 1](https://user-images.githubusercontent.com/10144772/92253326-5b76a600-ee9d-11ea-9675-00b38c6b2cff.png)

Did something happen that would cause a URL overwrite when you switched to live?

**Comment by proggeramlug** [comment] 2020-09-04 19:36
Hmm, that is an issue with the URL structure - I'll tell Armin about it. But we can fix it by giving random names to our files. Try again, we are now giving random names.

**Closed** 2020-10-09 14:25 UTC
Labels: enhancement
